export const GET_FLASHCARDS = 'GET_FLASHCARDS';
export const ADD_FLASHCARD = 'ADD_FLASHCARD';
export const DELETE_FLASHCARD = 'DELETE_FLASHCARD'; 
export const FLASHCARDS_LOADING = 'FLASHCARDS_LOADING'; 